// client/src/Login.tsx
import {Link, useNavigate } from "react-router";
import { UserContext } from "./UserContext";
import { useContext } from "react";


const Login = () => {
    const context = useContext(UserContext);
    const navigate = useNavigate();
    // console.log(context?.user);
    function handleSubmit(event: {
        target: any; preventDefault: any;
    }) {
        event.preventDefault();
        const formName = event.target;
        // console.log(formName.email.value, formName.pass.value);
        fetch('http://localhost:3000/user/' + formName.email.value)
        .then(res => res.json())
        .then(data => {
            if (data.password == formName.pass.value) {
                formName.email.value = '';
                formName.pass.value = '';
                document.getElementById('my_modal_2')?.classList.add('modal-open');
                setTimeout(() => {
                  document.getElementById('my_modal_2')?.classList.remove('modal-open');
                  localStorage.clear();
                  localStorage.setItem('user_id', data.user_id);
                  localStorage.setItem('name', data.name);
                  localStorage.setItem('email', data.email);
                  context?.setUser({user_id: data.user_id, name: data.name, email: data.email});
                  navigate('/');
              }, 1000);
            } else {
                document.getElementById('my_modal_1')?.classList.add('modal-open');
            }
        })
    }
    function closeModal() {
        document.getElementById('my_modal_1')?.classList.remove('modal-open');
    }
    return (
        <div className="p-8 pt-0">
            <form className="border-2 p-6 rounded-lg w-1/2 mx-auto mt-4" onSubmit={handleSubmit}>
                <p className="text-2xl mb-4 font-medium">Log In</p>
                <label htmlFor="email" className="font-medium">Email</label><br />
                <input type="email" id="email" name="email" className="border border-gray-400 rounded text-sm p-1 w-full" required/><br />
                <label htmlFor="pass" className="font-medium">Password</label><br />
                <input type="password" id="pass" name="pass" className="border border-gray-400 rounded text-sm p-1 w-full" required/><br />
                <input type="submit" className="btn btn-warning my-4 w-full" value="Login" />
                <p className="text-center mb-2 text-slate-400">New to movie review?</p>
                <hr />
                <Link to='/register'><button type="button" className="btn mt-4 w-full">Create your account</button></Link>
            </form>
<dialog id="my_modal_1" className="modal">
  <div className="modal-box">
    <p className="py-4 text-red-500 font-medium text-center">Email or Password didn't match!</p>
    <div className="">
      <form method="dialog" className="text-center">
        <button className="btn" onClick={closeModal}>Close</button>
      </form>
    </div>
  </div>
</dialog>
<dialog id="my_modal_2" className="modal">
  <div className="modal-box">
    <p className="py-4 font-medium text-center">Login successful!</p>

  </div>
</dialog>
        </div>
    );
};

export default Login;

// client/angular/src/app/login/login.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, ActivatedRoute, Router } from '@angular/router';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { UserService } from '../services/userServices/user.service';
import { GlobalStateService } from '../services/globalServices/global-state.service';
import { ToastersComponent } from './toasters/toasters.component';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, RouterModule, ReactiveFormsModule, ToastersComponent],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})

export class LoginComponent {
  route: ActivatedRoute = inject(ActivatedRoute);
  authenticationService = inject(UserService);
  globalStateService = inject(GlobalStateService);

  applyForm = new FormGroup({
    email: new FormControl(''),
    pass: new FormControl(''),
  });

  loggedInStatus = false;
  showLoginToaster = false;
  showErrorToaster = false;

  constructor(private stateService: GlobalStateService, private router: Router) {
    this.stateService.user$.subscribe((user) => {
      if (user) {
        this.loggedInStatus = true;
      }
    });
  }

  openToaster(type: string): void {
    if (type === 'login') this.showLoginToaster = true;
    if (type === 'error') this.showErrorToaster = true;
    this.closeToaster(type);
  }

  closeToaster(type: string, delay: number = 2500): void {
    setTimeout(() => {
      if (type === 'login') this.showLoginToaster = false;
      if (type === 'error') this.showErrorToaster = false;
    }, delay);
  }

  async submitApplication() {
    if (this.applyForm.value.email && this.applyForm.value.pass) {
      const response = await this.authenticationService.userLogin(this.applyForm.value.email, this.applyForm.value.pass);
      if (response.user_id && response.password == this.applyForm.value.pass) {
        localStorage.clear();
        localStorage.setItem('user_id', response.user_id);
        localStorage.setItem('name', response.name);
        localStorage.setItem('email', response.email);
        this.globalStateService.setUser(response);
        this.openToaster('login');
        setTimeout(() => {
          this.router.navigate(['/']);
        }, 3000);
        this.applyForm.reset();
      }
    } else {
      this.openToaster('error');
    }
  }
}

<div class="p-8">
    <!-- toasters -->
    <app-toasters
        [showLoginToaster]="showLoginToaster"
        [showErrorToaster]="showErrorToaster">
    </app-toasters>

    <form class="border-2 p-6 rounded-lg w-2/5 mx-auto mt-4"
        [formGroup]="applyForm" (submit)="submitApplication()">
        <p class="text-2xl mb-4 font-medium text-center">Log In</p>
        <label for="email" class="font-medium">Email</label><br />
        <input type="email" id="email" formControlName="email"
            class="border border-gray-400 rounded text-sm p-1 w-full"
            required /><br />
        <label for="pass" class="font-medium">Password</label><br />
        <input type="password" id="pass" formControlName="pass"
            class="border border-gray-400 rounded text-sm p-1 w-full"
            required /><br />
        <!-- <p class={showAlert_3? "text-center mt-2 text-red-500" : 
         "text-center mt-2 text-red-500 hidden"}><b>Email or Password didn't match!</b></p> -->
        <!-- <p class={showAlert_2? "text-center mt-2 text-red-500" : 
         "text-center mt-2 text-red-500 hidden"}><b>User isn't registered!</b></p> -->
        <input type="submit" class="btn btn-warning my-4 w-full"
            value="Login" />
        <p class="text-center mb-2 text-slate-400">New to movie review?</p>
        <hr />
        <a [routerLink]="['/register']"><button type="button"
                class="btn mt-4 w-full">Create your account</button></a>
    </form>
    <div class="toast toast-top toast-end">
    </div>
