// client/react/src/components/CreateMovie.tsx
import React, { useState, useContext, useEffect } from "react";
import { useLocation, useNavigate } from "react-router";
import { UserContext } from "../contexts/UserContext";
import { Genre } from "../interfaces/home";
import { MovieData, MovieFormProps } from "../interfaces/movieForm";
import { getAllGenres, createNewGenre } from "../services/genreService";
import { createMovie } from "../services/movieService";


const MovieForm: React.FC<MovieFormProps> = ({ setHomeRefresh, setListRefresh, setShowNavModal, setShowFirstModal }) => {
  const content = useContext(UserContext);
  const location = useLocation();
  const navigate = useNavigate();
  const [genres, setGenres] = useState<Genre[]>([]);
  const [genreReloader, setGenreReloader] = useState(0);
  const [showIN, setShowIN] = useState(false);
  const [showGN, setShowGN] = useState(false);
  const [formData, setFormData] = useState<MovieData>({
    title: "",
    img: "",
    desc: "",
    release_yr: "",
    director: "",
    length: "",
    producer: "",
    genre: [],
  });

  const [selectedGenres, setSelectedGenres] = useState<string[]>([]);
  const [newGenre, setNewGenre] = useState("");
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [uniqueTitleError, setUniqueTitleError] = useState(false);
  async function getGenres() {
    const res = await getAllGenres();
    setGenres(res);
  }
  useEffect(() => {
    getGenres();
  }, [genreReloader]);

  const handleInputChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    setUniqueTitleError(false);
  };

  const handleGenreChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const value = e.target.value;
    if (!selectedGenres.includes(value) && value != "Select a genre") {
      setShowGN(false);
      setSelectedGenres((prev) => [...prev, value]);
    }
  };

  const handleRemoveGenre = (genre: string) => {
    setSelectedGenres((prev) => prev.filter((g) => g !== genre));
  };

  const handleAddNewGenre = async () => {
    if (newGenre.trim() && !genres.find((x) => x.genre === newGenre)) {
      const response = await createNewGenre({ genre: newGenre });
      if (response.genre_id) {
        setNewGenre("");
        setGenreReloader(genreReloader + 1);
      }
    }
  };

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setImageFile(file);
      setImagePreview(URL.createObjectURL(file));
    }
  };

  const handleCancelImage = () => {
    setImageFile(null);
    setImagePreview(null);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (imageFile) {
      setShowIN(false);

      if (selectedGenres.length > 0) {
        setShowGN(false);
        // Upload image first
        const formDataImage = new FormData();
        formDataImage.append("image", imageFile);

        try {
          const imageResponse = await fetch("http://localhost:3000/upload", {
            method: "POST",
            body: formDataImage,
          });

          const imageData = await imageResponse.json();

          if (imageData.filePath) {
            // Update form data with image URL and selected genres
            const updatedFormData = {
              ...formData,
              img: imageData.filePath,
              genre: selectedGenres,
            };
            // console.log(JSON.stringify({ user_id: content?.user?.user_id, ...updatedFormData }));
            // Submit movie data
            const movie = await createMovie({
              user_id: content?.user?.user_id,
              ...updatedFormData,
            });
            // console.log(movie);
            if (movie.movie?.movie_id) {
              setFormData({
                title: "",
                img: "",
                desc: "",
                release_yr: "",
                director: "",
                length: "",
                producer: "",
                genre: [],
              });
              setImageFile(null);
              setImagePreview(null);
              setSelectedGenres([]);
              if (location.pathname == "/") {
                setHomeRefresh((prev) => prev + 1);
              } else if (location.pathname == "/user") {
                setListRefresh((prev) => prev + 1);
              }
              setShowNavModal(0);
              setShowFirstModal(true);
              setTimeout(() => {
                setShowFirstModal(false);
                if (location.pathname != '/' && location.pathname != '/user') { navigate('/user'); }
              }, 1500);
            } else {
              if (movie.error == 'title must be unique') {
                setUniqueTitleError(true);
                console.log(movie.error)
              } else {
                console.log(movie)
              }
            }
          }
        } catch (error) {
          console.error("Error during upload:", error);
        }
      } else {
        setShowGN(true);
      }
    } else {
      setShowIN(true);
    }
  };

  return (
    <div className="p-6 mx-auto">
      <h1 className="text-2xl font-bold mb-5">Create New Movie Entry</h1>
      <form onSubmit={handleSubmit} className="space-y-4">
        {uniqueTitleError && <p className="text-red-600 text-center">This title already exists!</p>}
        <input
          type="text"
          name="title"
          value={formData.title}
          onChange={handleInputChange}
          placeholder="Movie Title"
          className="input input-bordered w-full h-full py-1" style={{marginTop: uniqueTitleError? '10px' : 'auto'}}
          required
        />

        <textarea
          name="desc"
          value={formData.desc}
          onChange={handleInputChange}
          placeholder="Description"
          className="textarea textarea-bordered w-full"
        />
        <div className="flex justify-between">
        <input
          type="number"
          name="release_yr"
          value={formData.release_yr}
          onChange={handleInputChange}
          placeholder="Release Year"
          className="input input-bordered h-full py-1"
          required style={{width: '49%'}}
          max="9999"
        />

        <input
          type="number"
          name="length"
          value={formData.length}
          onChange={handleInputChange}
          placeholder="Length (minutes)"
          className="input input-bordered h-full py-1"
          required style={{width: '49%'}}
        />
        </div>

        <input
          type="text"
          name="director"
          value={formData.director}
          onChange={handleInputChange}
          placeholder="Director"
          className="input input-bordered me-2 h-full py-1"
          style={{width: '49%'}}
        />

        <input
          type="text"
          name="producer"
          value={formData.producer}
          onChange={handleInputChange}
          placeholder="Producer"
          className="input input-bordered h-full py-1"
          style={{width: '49%'}}
        />

        <section className="flex justify-between items-start">
        <div className="space-y-2" style={{width: '49%'}}>
          {genres.length > 0 && (
            <select
              onChange={handleGenreChange}
              className="select select-bordered w-full h-full min-h-0"
            >
              <option>Select a genre</option>
              {genres.map((genre) => (
                <option key={genre.genre_id} value={genre.genre}>
                  {genre.genre}
                </option>
              ))}
            </select>
          )}

          <p
            id="genre-notification"
            className={showGN ? "text-red-500 text-center" : "text-red-500 text-center hidden"}
          >
            <b>Genre must be added!</b>
          </p>
          <div className="flex flex-wrap gap-2">
            {selectedGenres.map((genre) => (
              <div key={genre} className="badge badge-ghost gap-1">
                {genre}
                <button
                  type="button"
                  onClick={() => handleRemoveGenre(genre)}
                  className="btn btn-ghost btn-xs"
                >
                  ✕
                </button>
              </div>
            ))}
          </div>
        </div>

        <div className="flex items-center space-x-2">
          <input
            type="text"
            value={newGenre}
            onChange={(e) => setNewGenre(e.target.value)}
            placeholder="Add new genre"
            className="input input-bordered flex-1 h-full py-1"
          />
          <button type="button" onClick={handleAddNewGenre} className="btn h-full py-2 min-h-0">
            Add
          </button>
        </div>
        </section>

        {/* Image Upload Section */}
        {!imageFile && (
          <>
            <label className="btn btn-block">
              Select Image
              <input
                type="file"
                className="hidden"
                onChange={handleImageChange}
                accept="image/*"
              />
            </label>
            <p
              id="img-notification"
              className={showIN ? "text-red-500 text-center" : "text-red-500 text-center hidden"}
            >
              <b>Image is required!!</b>
            </p>
          </>
        )}

        {/* Preview Section */}
        {imagePreview && (
          <div className="card w-96 bg-base-100 shadow-xl mx-auto">
            <figure>
              <img
                src={imagePreview}
                alt="Preview"
                className="rounded-t-lg max-h-60 object-cover"
              />
            </figure>
            <div className="card-body">
              <h2 className="card-title">Image Preview</h2>
              <div className="card-actions justify-end gap-2">
                <button
                  type="button"
                  className="btn btn-error text-white"
                  onClick={handleCancelImage}
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        )}
      <div className="flex justify-between">
      <button type="submit" className="btn" style={{width: '49%'}}>
          Submit
        </button>
        <button
          type="button"
          className="btn" style={{width: '49%'}}
          onClick={() => {
            document
              .getElementById("img-notification")
              ?.classList.add("hidden");
            setShowNavModal(0);
            document
              .getElementById("genre-notification")
              ?.classList.add("hidden");
            setShowIN(false);
            setShowNavModal(0);
            setShowGN(false);
          }}
        >
          Cancel
        </button>
      </div>
      </form>
    </div>
  );
};

export default MovieForm;

// client/angular/src/app/pages/create-movie/create-movie.component.ts
import { Router } from "@angular/router";
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormsModule, ReactiveFormsModule } from "@angular/forms";
import { FormBuilder, FormGroup, Validators } from "@angular/forms";
import { GenreService } from "src/app/services/genreServices/genre.service";
import { MovieService } from "src/app/services/movieServices/movie.service";
import { GlobalStateService } from "src/app/services/globalServices/global-state.service";

@Component({
  selector: "app-create-movie",
  standalone: true,
  imports: [FormsModule, CommonModule, ReactiveFormsModule],
  templateUrl: "./create-movie.component.html",
  styleUrls: ["./create-movie.component.css"],
})
export class CreateMovieComponent {
  movieForm: FormGroup;
  genres: any[] = [];
  selectedGenres: string[] = [];
  newGenre: string = "";
  imageFile: File | null = null;
  imagePreview: string | null = null;
  uniqueTitleError: boolean = false;

  constructor(
    private fb: FormBuilder,
    private movieService: MovieService,
    private genreService: GenreService,
    public router: Router,
    private stateService: GlobalStateService
  ) {
    this.movieForm = this.fb.group({
      title: ["", [Validators.required]],
      desc: [""],
      release_yr: ["", [Validators.required, Validators.max(9999)]],
      director: [""],
      length: ["", [Validators.required]],
      producer: [""],
    });
  }

  ngOnInit(): void {
    this.getGenres();
  }

  getGenres(): void {
    this.genreService.getAllGenres().subscribe((res) => {
      this.genres = res;
    });
  }

  handleGenreChange(event: any): void {
    const value = event.target.value;
    if (!this.selectedGenres.includes(value) && value !== "Select a genre") {
      this.selectedGenres.push(value);
    }
  }

  handleRemoveGenre(genre: string): void {
    this.selectedGenres = this.selectedGenres.filter((g) => g !== genre);
  }

  handleAddNewGenre(): void {
    if (
      this.newGenre.trim() &&
      !this.genres.some((g) => g.genre === this.newGenre)
    ) {
      this.genreService
        .createNewGenre({ genre: this.newGenre })
        .subscribe(() => {
          this.getGenres();
          this.newGenre = "";
        });
    }
  }

  handleImageChange(event: any): void {
    const file = event.target.files[0];
    if (file) {
      this.imageFile = file;
      this.imagePreview = URL.createObjectURL(file);
    }
  }

  handleCancelImage(): void {
    this.imageFile = null;
    this.imagePreview = null;
  }

  handleSubmit(): void {
    if (
      this.movieForm.invalid ||
      !this.imageFile ||
      this.selectedGenres.length === 0
    ) {
      return;
    }

    const formData = new FormData();
    formData.append("image", this.imageFile);
    this.movieService.uploadImage(formData).subscribe((imageData: any) => {
      const movieData = {
        ...this.movieForm.value,
        img: imageData.filePath,
        genre: this.selectedGenres,
        user_id: this.stateService.getUser()?.user_id,
      };

      this.movieService.createMovie(movieData).subscribe((movie) => {
        console.log("Create: ", movie);
        if (movie) {
          this.router.navigate(["/"]);
        } else if (movie.error === "title must be unique") {
          this.uniqueTitleError = true;
        }
      });
    });
  }
}

<div class="p-6 px-8 mx-auto max-w-4xl">
  <h1 class="text-2xl font-bold mb-5">Create New Movie Entry</h1>
  <form [formGroup]="movieForm" (ngSubmit)="handleSubmit()" class="space-y-4">
    <p *ngIf="uniqueTitleError" class="text-red-600 text-center">This title already exists!</p>
    
    <!-- Title and Description now at half width -->
    <div class="flex gap-4">
      <input
        formControlName="title"
        placeholder="Movie Title"
        class="input input-bordered h-full py-1 flex-1"
        required
      />
      <textarea
        formControlName="desc"
        placeholder="Description"
        class="textarea textarea-bordered flex-1"
      ></textarea>
    </div>
    
    <!-- Release Year and Length -->
    <div class="flex gap-4">
      <input
        type="number"
        formControlName="release_yr"
        placeholder="Release Year"
        class="input input-bordered h-full py-1 flex-1"
        required
        max="9999"
      />
      <input
        type="number"
        formControlName="length"
        placeholder="Length (minutes)"
        class="input input-bordered h-full py-1 flex-1"
        required
      />
    </div>
    
    <!-- Director and Producer -->
    <div class="flex gap-4">
      <input
        formControlName="director"
        placeholder="Director"
        class="input input-bordered h-full py-1 flex-1"
      />
      <input
        formControlName="producer"
        placeholder="Producer"
        class="input input-bordered h-full py-1 flex-1"
      />
    </div>
    
    <div class="flex gap-4">
      <div class="flex-1">
        <select 
          (change)="handleGenreChange($event)" 
          class="select select-bordered w-full h-full min-h-0"
        >
          <option>Select a genre</option>
          <option *ngFor="let genre of genres" [value]="genre.genre">{{ genre.genre }}</option>
        </select>
        <p *ngIf="selectedGenres.length === 0" class="text-red-500 text-center mt-2">
          <b>Genre must be added!</b>
        </p>
      </div>
      
      <div class="flex gap-2 flex-1">
        <input
          [(ngModel)]="newGenre"
          placeholder="Add new genre"
          class="input input-bordered flex-1 h-full py-1"
        />
        <button type="button" (click)="handleAddNewGenre()" class="btn h-full py-2 min-h-0">Add</button>
      </div>
    </div>

    <!-- Selected genres display -->
    <div class="flex flex-wrap gap-2">
      <div *ngFor="let genre of selectedGenres" class="badge badge-ghost gap-1">
        {{ genre }}
        <button type="button" (click)="handleRemoveGenre(genre)" class="btn btn-ghost btn-xs">✕</button>
      </div>
    </div>
    
    <!-- Image upload section - centered and half width -->
    <div class="flex justify-center">
      <label *ngIf="!imageFile" class="btn w-1/2">
        Select Image
        <input type="file" class="hidden" (change)="handleImageChange($event)" accept="image/*" />
      </label>
    </div>
    
    <p *ngIf="!imageFile" class="text-red-500 text-center">
      <b>Image is required!!</b>
    </p>
    
    <div *ngIf="imagePreview" class="card w-96 bg-base-100 shadow-xl mx-auto">
      <figure>
        <img [src]="imagePreview" alt="Preview" class="rounded-t-lg max-h-60 object-cover" />
      </figure>
      <div class="card-body">
        <h2 class="card-title">Image Preview</h2>
        <div class="card-actions justify-end gap-2">
          <button type="button" class="btn btn-error text-white" (click)="handleCancelImage()">Cancel</button>
        </div>
      </div>
    </div>
    
    <!-- Submit and Cancel buttons -->
    <div class="flex gap-4">
      <button type="submit" class="btn flex-1">Submit</button>
      <button type="button" class="btn flex-1" (click)="router.navigate(['/'])">Cancel</button>
    </div>
  </form>
</div>
